version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: grandline-genesis-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: grandline_genesis
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./volumes/grandline-genesis-mysql:/var/lib/mysql